[package]
name = "Pos"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlite = "0.30.4"
json = "0.12.4"
regex = "1.8.1"
